###
# this works and returns "Hello World"
GET http://localhost:3000 HTTP/1.1

###
# this works and returns all the items
GET http://localhost:3000/items HTTP/1.1


###
GET http://localhost:3000/items/62eed70580b52089d9dcd733 HTTP/1.1


###
POST http://localhost:3000/items HTTP/1.1
Content-Type: application/json

{
  "name": "Item Three",
  "qty": 23,
  "description": "This is item three"
}

###
DELETE http://localhost:3000/items/62eed70580b52089d9dcd733 HTTP/1.1

###
PUT http://localhost:3000/items/62eed6b080b52089d9dcd72f HTTP/1.1
Content-Type: application/json

{
   "qty": 30
}